---
- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | default('change_me') }}.jsrh.redhat.lab"
    use: systemd

# - name: Clear registration settings
#   community.general.redhat_subscription:
#     state: absent
#     server_insecure: true

# - name: Register to Sattellite with activation key
#   community.general.redhat_subscription:
#     state: present
#     server_insecure: true
#     force_register: true
#     activationkey: RHEL8_preprod
#     org_id: DemoLab

- name: Register with Satellite template
  ansible.builtin.shell: >
    curl -sS --insecure 
    'https://satellite.redhat.lab/register?activation_keys=RHEL8_preprod&location_id=5&operatingsystem_id=1
    &organization_id=1&setup_insights=false&setup_remote_execution=false&update_packages=false' 
    -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNSwiaWF0IjoxNzA3OTgzNzM0LCJqdGkiOiIwNTBh
    NThhMDNiZTFhYzg5NTNjNDk0YzZhZmUyMjk5MjVkOTJkNDc1N2Y3MDk3NDdlODY3N2RlODM4MDIxMGM0IiwiZXhwIjoxNzA3OTk4MTM0
    LCJzY29wZSI6InJlZ2lzdHJhdGlvbiNnbG9iYWwgcmVnaXN0cmF0aW9uI2hvc3QifQ.
    h17JHziEvQ34UNn2wnA5D3IeDUFU4MRey0aEhoi5Y7U' | bash

- name: Install Epel
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: true
