---
- name: Set machine hostname
  ansible.builtin.hostname:
<<<<<<< HEAD
    name: "{{ asible_hostname | default('change_me')}}.jsrh.redhat.lab }}"
=======
    name: "{{inventory_hostname | default('change_me')}}.jsrh.redhat.lab"
>>>>>>> fb2bd8207c79151d6cb6868d499bbfd667313619
    use: systemd

- name: Clear registration settings
  community.general.redhat_subscription:
    state: absent

- name: Register to Sattellite with activation key
  community.general.redhat_subscription:
    state: present
    server_insecure: true
    force_register: true
    activationkey: RHEL8_preprod
    org_id: DemoLab

- name: Install Epel
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: yes