---
- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | default('change_me') }}.jsrh.redhat.lab"
    use: systemd

- name: Register with Satellite template
  ansible.builtin.script: ./files/satreg.sh
  args:
    executable: /bin/bash

- name: Add Epel Repo
  ansible.builtin.command: rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
